image: "ruby:2.3"

services:
  - mysql:latest
  - redis:latest
  - postgres:latest

variables:
  POSTGRES_DB: database_name

cache:
  paths:
    - vendor/ruby

# This is a basic example for a gem or script which doesn't use
# services such as redis or postgres
before_script:
  - ruby -v
  - apt-get update -q && apt-get install nodejs -yqq
  - gem install bundler  --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rspec:
  script:
  - rspec spec

rails:
  # variables:
  # DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - bundle exec rake db:migrate
  - bundle exec rake db:seed
  - bundle exec rake test
